apiVersion: v1
kind: Service
metadata:
  name: three-tier-frontend-svc
  namespace: hsaab
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 32322
  selector:
    app: three-tier-frontend-deployment

