apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.namespace}}-three-tier-frontend-deployment
  namespace: {{.Values.namespace}}
  annotations:
    kubernetes.io/depends-on: "{{.Values.namespace}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.namespace}}-three-tier-frontend-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.namespace}}-three-tier-frontend-deployment
    spec:
      containers:
      - name: {{.Values.namespace}}-three-tier-frontend
        image: hsaab/three-tier-app-frontend:{{.Values.namespace}}-{{.Values.sequenceId}}
        ports:
        - containerPort: 80
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"