apiVersion: v1
kind: Service
metadata:
  name: {{.Values.namespace}}-three-tier-frontend-svc
  namespace: {{.Values.namespace}}
  annotations:
    kubernetes.io/depends-on: "{{.Values.namespace}}"
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 32322
  selector:
    app: {{.Values.namespace}}-three-tier-frontend-deployment

