apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.namespace}}-three-tier-backend-deployment
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.namespace}}-three-tier-backend-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.namespace}}-three-tier-backend-deployment
    spec:
      containers:
      - name: {{.Values.namespace}}-three-tier-backend
        image: hsaab/three-tier-app-backend:{{.Values.namespace}}:{{.Values.executionId}}
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          value: "production"
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"