apiVersion: v1
kind: Service
metadata:
  name: three-tier-backend-svc
  namespace: hsaab
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: three-tier-backend-deployment

