apiVersion: v1
kind: Service
metadata:
  name: {{.Values.namespace}}-three-tier-backend-svc
  namespace: {{.Values.namespace}}
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: {{.Values.namespace}}-three-tier-backend-deployment

