apiVersion: v1
kind: Service
metadata:
  name: hsaab-react-demo-app-svc
  namespace: hsaab
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 32321
  selector:
    app: hsaab-react-demo-app-deployment