apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsaab-react-demo-app-deployment
  namespace: hsaab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsaab-react-demo-app-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hsaab-react-demo-app-deployment
    spec:
      containers:
      - name: hsaab-react-demo-app
        image: hsaab/react-demo-app:1
        ports:
        - containerPort: 80
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"