apiVersion: v1
kind: Service
metadata:
  name: hsaab-react-split-demo-service
  namespace: hsaab
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: hsaab-react-split-demo-deployment
