apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.namespace}}-react-demo-app-deployment
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.namespace}}-react-demo-app-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.namespace}}-react-demo-app-deployment
    spec:
      containers:
      - name: {{.Values.namespace}}-react-demo-app
        image: hsaab/react-split-demo:33
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"