apiVersion: v1
kind: Service
metadata:
  name: {{.Values.namespace}}-react-split-demo-service
  namespace: {{.Values.namespace}} 
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{.Values.namespace}}-react-split-demo-deployment
