apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.namespace}}-react-split-demo-deployment
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.namespace}}-react-split-demo-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.namespace}}-react-split-demo-deployment
    spec:
      containers:
      - name: {{.Values.namespace}}-react-split-demo
        image: hsaab/react-split-demo:32
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        env:
        - name: REACT_APP_SPLIT_SDK_KEY
          valueFrom:
            secretKeyRef:
              name: split-sdk-key
              key: key  