apiVersion: v1
kind: Service
metadata:
  name: hsaab-react-demo-app-svc
  namespace: hsaab
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: hsaab-react-demo-app-deployment

